name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: C:\flutter\.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.x"

      - name: Install Dependencies
        run: flutter pub get

      - name: Cache Dependency Packages
        uses: actions/cache@v2
        with:
          path: C:\flutter\.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Build Web App
        run: flutter build web

      - name: Deploy to Kratosgado.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          cname: kratosgado.github.io
          user_name: Kratosgado
          user_email: mbeahessilfieprince@gmail.com
